version: '3'
name: steffi
services:
  steffi:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "23000:3000"
    volumes:
      - ./:/app
    command: sh -c "npm install; npm run prebuild; npm run start:debug"
    tty: true
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 25432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
volumes:
  db-store:
